export const districts = [
  { id: 'colombo', name: 'Colombo' },
  { id: 'gampaha', name: 'Gampaha' },
  { id: 'kalutara', name: 'Kalutara' },
  { id: 'kandy', name: 'Kandy' },
  { id: 'matale', name: 'Matale' },
  { id: 'nuwaraeliya', name: 'Nuwara Eliya' },
  { id: 'galle', name: 'Galle' },
  { id: 'matara', name: 'Matara' },
  { id: 'hambantota', name: 'Hambantota' },
  { id: 'jaffna', name: 'Jaffna' },
  { id: 'kilinochchi', name: 'Kilinochchi' },
  { id: 'mannar', name: 'Mannar' },
  { id: 'mullaitivu', name: 'Mullaitivu' },
  { id: 'vavuniya', name: 'Vavuniya' },
  { id: 'puttalam', name: 'Puttalam' },
  { id: 'kurunegala', name: 'Kurunegala' },
  { id: 'kegalle', name: 'Kegalle' },
  { id: 'ratnapura', name: 'Ratnapura' },
  { id: 'badulla', name: 'Badulla' },
  { id: 'monaragala', name: 'Monaragala' },
  { id: 'ampara', name: 'Ampara' },
  { id: 'batticaloa', name: 'Batticaloa' },
  { id: 'trincomalee', name: 'Trincomalee' },
  { id: 'polonnaruwa', name: 'Polonnaruwa' },
  { id: 'anuradhapura', name: 'Anuradhapura' },
];

export const cities = {
  colombo: ['Colombo 1', 'Colombo 2', 'Colombo 3', 'Colombo 4', 'Colombo 5', 'Colombo 6', 'Colombo 7', 'Colombo 8', 'Colombo 9', 'Colombo 10', 'Colombo 11', 'Colombo 12', 'Colombo 13', 'Colombo 14', 'Colombo 15', 'Dehiwala', 'Mount Lavinia', 'Moratuwa', 'Kaduwela', 'Maharagama', 'Battaramulla', 'Nugegoda', 'Piliyandala', 'Kottawa', 'Homagama'],
  gampaha: ['Gampaha', 'Negombo', 'Kandana', 'Ja-Ela', 'Katunayake', 'Seeduwa', 'Minuwangoda', 'Veyangoda', 'Wattala', 'Kiribathgoda', 'Ganemulla', 'Ragama', 'Kelaniya', 'Biyagama', 'Mabola'],
  kalutara: ['Kalutara', 'Panadura', 'Horana', 'Beruwala', 'Aluthgama', 'Mathugama', 'Bandaragama', 'Ingiriya', 'Wadduwa', 'Katukurunda'],
  kandy: ['Kandy', 'Peradeniya', 'Gampola', 'Nawalapitiya', 'Kadugannawa', 'Wattegama', 'Kundasale', 'Katugastota', 'Pallekele', 'Madawala', 'Pilimathalawa'],
  matale: ['Matale', 'Dambulla', 'Sigiriya', 'Galewela', 'Ukuwela', 'Pallepola', 'Laggala', 'Wilgamuwa'],
  nuwaraeliya: ['Nuwara Eliya', 'Hatton', 'Talawakelle', 'Bogawantalawa', 'Welimada', 'Haputale', 'Bandarawela', 'Ginigathhena', 'Ragala', 'Kotagala'],
  galle: ['Galle', 'Ambalangoda', 'Hikkaduwa', 'Elpitiya', 'Baddegama', 'Ahangama', 'Boossa', 'Gintota', 'Gonapinuwala'],
  matara: ['Matara', 'Weligama', 'Mirissa', 'Dickwella', 'Kamburupitiya', 'Akuressa', 'Pallebedda', 'Deniyaya', 'Udugama'],
  hambantota: ['Hambantota', 'Tangalle', 'Beliatta', 'Tissamaharama', 'Ambalantota', 'Ranna', 'Weerawila', 'Kataragama', 'Suriyawewa'],
  jaffna: ['Jaffna', 'Nallur', 'Chavakachcheri', 'Kankesanthurai', 'Point Pedro', 'Valvettithurai', 'Vaddukoddai', 'Velanai', 'Mallakam', 'Kopay'],
  kilinochchi: ['Kilinochchi', 'Paranthan', 'Kandavalai', 'Poonakary', 'Karachchi', 'Uduppiddy'],
  mannar: ['Mannar', 'Vankalai', 'Pesalai', 'Madhu', 'Murunkan', 'Nanattan'],
  mullaitivu: ['Mullaitivu', 'Puthukudiyiruppu', 'Oddusuddan', 'Karuppaddamurippu', 'Mankulam'],
  vavuniya: ['Vavuniya', 'Vengalacheddikulam', 'Sasthirikoodal', 'Nelukkulam', 'Kanakarayankulam'],
  puttalam: ['Puttalam', 'Chilaw', 'Wennappuwa', 'Marawila', 'Nattandiya', 'Mundalama', 'Anamaduwa', 'Kakkapalliya', 'Kalpitiya'],
  kurunegala: ['Kurunegala', 'Kuliyapitiya', 'Nikaweratiya', 'Pannala', 'Galgamuwa', 'Mawathagama', 'Ibbagamuwa', 'Narammala', 'Rideegama', 'Maho'],
  kegalle: ['Kegalle', 'Mawanella', 'Rambukkana', 'Warakapola', 'Deraniyagala', 'Karawanella', 'Aranayaka', 'Dehiowita', 'Yatiyantota', 'Kitulgala'],
  ratnapura: ['Ratnapura', 'Balangoda', 'Embilipitiya', 'Pelmadulla', 'Kalawana', 'Erathna', 'Panamure', 'Kolonna', 'Ayagama', 'Weligepola'],
  badulla: ['Badulla', 'Bandarawela', 'Ella', 'Haputale', 'Welimada', 'Mahiyanganaya', 'Passara', 'Meegahakivula', 'Beragala', 'Sorabora', 'Lunugala'],
  monaragala: ['Monaragala', 'Bibile', 'Kataragama', 'Wellawaya', 'Thanamalvila', 'Sella Kataragama', 'Nakkala', 'Inginiyagala', 'Hambegamuwa'],
  ampara: ['Ampara', 'Kalmunai', 'Akkaraipattu', 'Batticaloa', 'Eravur', 'Kattankudy', 'Pottuvil', 'Samanthurai', 'Dehiattakandiya', 'Maha Oya'],
  batticaloa: ['Batticaloa', 'Kattankudy', 'Eravur', 'Kalkudah', 'Pattipalai', 'Vakarai', 'Kiran', 'Puliyanthivu', 'Odayam'],
  trincomalee: ['Trincomalee', 'Nilaveli', 'Kinniya', 'Muttur', 'Kantalai', 'Seruvila', 'Gomarankadawala', 'Pulmoddai'],
  polonnaruwa: ['Polonnaruwa', 'Minneriya', 'Hingurakgoda', 'Medirigiriya', 'Kaduruwela', 'Dimbulagala', 'Lankapura', 'Talawa', 'Pulasthigama'],
  anuradhapura: ['Anuradhapura', 'Mihintale', 'Kekirawa', 'Kebithigollewa', 'Galnewa', 'Nochchiyagama', 'Talawa', 'Eppawala', 'Galkulama', 'Rajanganaya']
};